# Generated by Django 4.0.4 on 2022-04-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases_ecuador_covid',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
